<?php
/**
 * PublicApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ory Kratos API
 *
 * Documentation for all public and administrative Ory Kratos APIs. Public and administrative APIs are exposed on different ports. Public APIs can face the public internet without any protection while administrative APIs should never be exposed without prior authorization. To protect the administative API port you should use something like Nginx, Ory Oathkeeper, or any other technology capable of authorizing incoming requests.
 *
 * The version of the OpenAPI document: 
 * Contact: hi@ory.sh
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PublicApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PublicApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for completeSelfServiceBrowserSettingsOIDCSettingsFlow
     *
     * Complete the Browser-Based Settings Flow for the OpenID Connect Strategy.
     *
     */
    public function testCompleteSelfServiceBrowserSettingsOIDCSettingsFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completeSelfServiceLoginFlowWithPasswordMethod
     *
     * Complete Login Flow with Username/Email Password Method.
     *
     */
    public function testCompleteSelfServiceLoginFlowWithPasswordMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completeSelfServiceRecoveryFlowWithLinkMethod
     *
     * Complete Recovery Flow with Link Method.
     *
     */
    public function testCompleteSelfServiceRecoveryFlowWithLinkMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completeSelfServiceRegistrationFlowWithPasswordMethod
     *
     * Complete Registration Flow with Username/Email Password Method.
     *
     */
    public function testCompleteSelfServiceRegistrationFlowWithPasswordMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completeSelfServiceSettingsFlowWithPasswordMethod
     *
     * Complete Settings Flow with Username/Email Password Method.
     *
     */
    public function testCompleteSelfServiceSettingsFlowWithPasswordMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completeSelfServiceSettingsFlowWithProfileMethod
     *
     * Complete Settings Flow with Profile Method.
     *
     */
    public function testCompleteSelfServiceSettingsFlowWithProfileMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completeSelfServiceVerificationFlowWithLinkMethod
     *
     * Complete Verification Flow with Link Method.
     *
     */
    public function testCompleteSelfServiceVerificationFlowWithLinkMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSchema
     *
     * .
     *
     */
    public function testGetSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSelfServiceError
     *
     * Get User-Facing Self-Service Errors.
     *
     */
    public function testGetSelfServiceError()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSelfServiceLoginFlow
     *
     * Get Login Flow.
     *
     */
    public function testGetSelfServiceLoginFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSelfServiceRecoveryFlow
     *
     * Get information about a recovery flow.
     *
     */
    public function testGetSelfServiceRecoveryFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSelfServiceRegistrationFlow
     *
     * Get Registration Flow.
     *
     */
    public function testGetSelfServiceRegistrationFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSelfServiceSettingsFlow
     *
     * Get Settings Flow.
     *
     */
    public function testGetSelfServiceSettingsFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSelfServiceVerificationFlow
     *
     * Get Verification Flow.
     *
     */
    public function testGetSelfServiceVerificationFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceBrowserLogoutFlow
     *
     * Initialize Browser-Based Logout User Flow.
     *
     */
    public function testInitializeSelfServiceBrowserLogoutFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceLoginViaAPIFlow
     *
     * Initialize Login Flow for API clients.
     *
     */
    public function testInitializeSelfServiceLoginViaAPIFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceLoginViaBrowserFlow
     *
     * Initialize Login Flow for browsers.
     *
     */
    public function testInitializeSelfServiceLoginViaBrowserFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceRecoveryViaAPIFlow
     *
     * Initialize Recovery Flow for API Clients.
     *
     */
    public function testInitializeSelfServiceRecoveryViaAPIFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceRecoveryViaBrowserFlow
     *
     * Initialize Recovery Flow for Browser Clients.
     *
     */
    public function testInitializeSelfServiceRecoveryViaBrowserFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceRegistrationViaAPIFlow
     *
     * Initialize Registration Flow for API clients.
     *
     */
    public function testInitializeSelfServiceRegistrationViaAPIFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceRegistrationViaBrowserFlow
     *
     * Initialize Registration Flow for browsers.
     *
     */
    public function testInitializeSelfServiceRegistrationViaBrowserFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceSettingsViaAPIFlow
     *
     * Initialize Settings Flow for API Clients.
     *
     */
    public function testInitializeSelfServiceSettingsViaAPIFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceSettingsViaBrowserFlow
     *
     * Initialize Settings Flow for Browsers.
     *
     */
    public function testInitializeSelfServiceSettingsViaBrowserFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceVerificationViaAPIFlow
     *
     * Initialize Verification Flow for API Clients.
     *
     */
    public function testInitializeSelfServiceVerificationViaAPIFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initializeSelfServiceVerificationViaBrowserFlow
     *
     * Initialize Verification Flow for Browser Clients.
     *
     */
    public function testInitializeSelfServiceVerificationViaBrowserFlow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeSession
     *
     * Revoke and Invalidate a Session.
     *
     */
    public function testRevokeSession()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for whoami
     *
     * Check Who the Current HTTP Session Belongs To.
     *
     */
    public function testWhoami()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
